### ISSUE TITLE
Error on `go get` [MacOSX]

### ISSUE THREAD

**Issue by ghigt** [rthornton128/goncurses#24]
I have this error:
```
# pkg-config --cflags ncurses form menu ncurses ncurses panel
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found
Package form was not found in the pkg-config search path.
Perhaps you should add the directory containing `form.pc'
to the PKG_CONFIG_PATH environment variable
No package 'form' found
Package menu was not found in the pkg-config search path.
Perhaps you should add the directory containing `menu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'menu' found
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found
Package panel was not found in the pkg-config search path.
Perhaps you should add the directory containing `panel.pc'
to the PKG_CONFIG_PATH environment variable
No package 'panel' found
pkg-config: exit status 1
```

I installed `ncurses` via `brew install ncurses`.
Do you have a solution?

**Comment by rthornton128** [comment]
Yes and no. This issue is specifically mentioned in the [wiki](https://github.com/rthornton128/goncurses/wiki/KnownIssues). This is covered in an [issue](https://github.com/Homebrew/homebrew-dupes/issues/396) at the homebrew project.

In my mind, you have the following options available to you:

* Adjust pkg-config to find the homebrew installation to locate the ncurses .pc files as instructed in the above linked issue
* You can use macports to install ncurses, which seems to work as expected
* Manually edit the sources to add the proper linker flags for cgo (another suggestion by homebrew)

I suggest reading the homebrew issue to understand their reasoning behind the behavior of the software.
