### ISSUE TITLE
How to make the libncurse dependency version independent ?

### ISSUE THREAD

**Issue by lamarios** [rthornton128/goncurses#46]
Not sure if the title is clear, here's my situation:
machine 1 -> Arch linux with libncurse6
machine 2 -> Ubuntu with libncurse5

I do my development on the Arch machine but run my application on my Ubuntu machine, the problem is that if i build it on the arch machine it can't run on the Ubuntu machine because it's looking for libncursesw.so.6. 

If i compile on my ubuntu machine from the source then it's ok.

Is there a way to change this so that it only requires libncurses of which ever version is available on the client system ?

**Comment by rthornton128** [comment]
The problem is that it appears you have two different API versions (5 and 6). You can't compile a library between (potentially) incompatible interfaces,

Perhaps this link will help? https://unix.stackexchange.com/questions/475/how-do-so-shared-object-numbers-work#476

You may want to look into semantic versioning of shared libraries but basically, as far as I'm aware, there is no solution to your problem short of installing compatible versions on each system. Arch is pretty progressive and it shouldn't be too hard to install ncurses5 on it. This would be my recommendation. You'll need to make sure you link against the correct library version if you keep both installed on your Arch system.

Looks like ncurses6 may be available in cosmic (18.10), though.

**Comment by lamarios** [comment]
Alright, thanks for the clarification. Let say i install both libncuses5 and 6 on my Arch machine, how do i decide which is needed at compile time ?
