### ISSUE TITLE
About window scrolling

### ISSUE THREAD

**Issue by shuiYe-704265085** [rthornton128/goncurses#66]
If there is content in the window that exceeds the height of the window, how to set the mouse to scroll to the content that exceeds the window? I tried to set scrollok, but it had no effect

**Comment by rthornton128** [comment]
I have not used mouse scrolling in NCurses so my guidance here is pretty limited. To my knowledge, mouse support has never been particularly great due to the age NCurses is. GonCurses is therefore, no exception.

Basically, if I understand the question correctly, if you want to scroll a window based on using a mouse wheel, you need to detect the mouse-wheel event. From what I found in this [StackOverflow issue](https://stackoverflow.com/questions/20566213/ncurses-mouse-wheel-scroll-up), it sounds like the result is not very satisfactory.

As for clicking some kind of scrollbar, you would need to detect a click event wherever your scroll button is located and then move the window (maybe using a pad) appropriately.

Last, if you what you are aiming to do is moving the mouse to the edge of the screen, you might be able to detect the mouse movement and get its location. If you determine the location to be the edge of the visible window, you could then scroll it.

Finally, to address `scrollok`, the NCurses documentation states:
>The scrollok option controls what happens when the cursor of a window is moved off the edge of the window or scrolling region, either as a result of a newline action on the bottom line, or typing the last character of the last line. 

Note that this is not the mouse cursor as we think of it but the typing (virtual?) cursor on the screen/window. That's what this option controls and why it's not working for you.

**Comment by shuiYe-704265085** [comment]
OK, I see what you mean. Thank you for your answer
